### ISSUE TITLE
Themes Errors with new Hubzilla version 

### ISSUE THREAD

**Issue by royalterra** [DeadSuperHero/hubzilla-themes#11]
Multiple Theme errors with new Hubzilla Versions Affected all the DeadDuperHero Themes

```

> Stack trace:, referer: https://myhub/view/theme/suckerberg/php/style.pcss
> [Wed Mar 09 15:07:13.277954 2016] [:error] [pid 2209] [client 81.96.213.209:58282] PHP   1. {main}() /var/www/myhub/index.php:0, referer: https://myhub/view/theme/suckerberg/php/style.pcss
> [Wed Mar 09 15:07:13.277963 2016] [:error] [pid 2209] [client 81.96.213.209:58282] PHP   2. Zotlabs\\Web\\Router->Dispatch() /var/www/myhub/index.php:161, referer: https://myhub/view/theme/suckerberg/php/style.pcss
> [Wed Mar 09 15:07:13.277968 2016] [:error] [pid 2209] [client 81.96.213.209:58282] PHP   3. view_init() /var/www/myhub/Zotlabs/Web/Router.php:137, referer: https://myhub/view/theme/suckerberg/php/style.pcss
> [Wed Mar 09 15:07:13.277974 2016] [:error] [pid 2209] [client 81.96.213.209:58282] PHP   4. require_once() /var/www/myhub/mod/view.php:13, referer: https://myhub/view/theme/suckerberg/php/style.pcss
> [Wed Mar 09 15:07:13.277979 2016] [:error] [pid 2209] [client 81.96.213.209:58282] PHP   5. require_once() /var/www/myhub/extend/theme/DeadSuperHeroThemes/suckerberg/php/style.php:3, referer: https://myhub/view/theme/suckerberg/php/style.pcss
> [Wed Mar 09 15:07:13.277984 2016] [:error] [pid 2209] [client 81.96.213.209:58282] PHP   6. set_pconfig() /var/www/myhub/view/theme/redbasic/php/style.php:222, referer: https://myhub/view/theme/suckerberg/php/style.pcss
> [Wed Mar 09 15:07:13.278008 2016] [:error] [pid 2209] [client 81.96.213.209:58282] PHP   7. array_key_exists() /var/www/myhub/include/config.php:295, referer: https://myhub/view/theme/suckerberg/php/style.pcss

```

**Comment by DeadSuperHero** [comment]
Hmm. Happy to look into this, do you think you could provide some screenshots? Are these visual errors?

**Comment by royalterra** [comment]
Dear Friend:
I look around and not show any visual error only in apache2 errors the issue I test with the old version of your themes and the new version and only happens if you have the Hubzilla Pull in previous versions of Hubzilla not show any error. Possible they change something in the hubzilla main theme  is now in clonflict

**Comment by DeadSuperHero** [comment]
Could you list the steps to recreate the problem, or what you used to find these errors? Also, is this something that's just showing up on your hub, or is it showing up on mine as well?

Just trying to find a good starting point for fixes.

**Comment by royalterra** [comment]
Recreate the problem:
Hubzilla Version last 24 hours is 2016-03-08.1330H - 1165
1.- activate example sucker
2.- Exit and go login Page 
3.- Look Apache2 Log You got that errors if you reload the page show the errors again.
4.- Login in Hubzilla Not show more error everything clear only show if you are not Login

Test 2.- In other Hubs
Hubzilla  Version 2016-02-12.1307H - 1161
1.- activate example sucker
2.- Exit and go login Page 
3.- Look Apache2 Log NO ERRORS  Reload the page show NO errors.
4.- Login in Hubzilla Not Error

That error only show in Hubzilla Version 2016-03-08.1330H - 1165

**Comment by DeadSuperHero** [comment]
Hm, might not be able to recreate on my end since I'm on Nginx. I'll try to dive into more of this soon.

**Comment by royalterra** [comment]
To me look more is a issue with the new changes in redbasic

**Comment by royalterra** [comment]
I make a small change in your file headerboard.php and now I not got more complaint errors
`$channel_id = (int)0;`

**Comment by royalterra** [comment]
Create a pull resquest

**Comment by DeadSuperHero** [comment]
Should be fixed with latest commit. Headerboard.php is not an essential widget, and is not used anywhere.
