### ISSUE TITLE
Suckerberg - Profile template needs customization

### ISSUE THREAD

**Issue by DeadSuperHero** [DeadSuperHero/hubzilla-themes#4]
So, this is a tricky one as well. Basically, to get the profile to be more "timeline-like", some customization to regions and templates will be necessary. This requires greater investment in understanding how RedMatrix templates are put together, but I've been assured that template overrides can be done within the theme directory.

**Comment by royalterra** [comment]
@DeadSuperHero I really like your themes but is not more easy have a framework like joomla have several all different . Where you can select modules and positions and not depends like now of the redbasic theme. I can make a economical donation if that help for motivation

**Comment by DeadSuperHero** [comment]
Can you clarify what you mean by that? Were you thinking perhaps of how
Elgg handles profile customization, where the different widgets can be
dragged into different positions?​

**Comment by royalterra** [comment]
Yes can be something like elgg have for the users side but can be also to for the admin for specify the positions and place the module can be activate or not in positions in the theme . And in joomla there very nice framework for Themes User  Admin is T3-framework can give you are idea the freedom have the admin for make nice changes in a theme
