### ISSUE TITLE
embedded video gets truncated

### ISSUE THREAD

**Issue by mrjive** [DeadSuperHero/hubzilla-themes#7]
Example: https://red.mrjive.eu/channel/mrjive/?f=&mid=31cc136d099b07ed1fbf78358a80c0d234f4cb83e331d6452cc209d730dfb5bb@red.mrjive.eu
when clicking on the video to see it, it is partly hidden

**Comment by mrjive** [comment]
oh, I was talking about sunbeam, didn't try it with other themes!

**Comment by DeadSuperHero** [comment]
This seems to be an ongoing problem with my existing themes - I'm not really sure how to fix it yet. If anyone has insights on fixing embeds, please let me know!

**Comment by royalterra** [comment]
@DeadSuperHero have you at boot.php there are variable for the size of embeds videos possible you have a conflict with that .

**Comment by DeadSuperHero** [comment]
I would love to resolve the embeds so that they look better. At the moment,
they're way too small. :(

I will look into what needs to happen for this.
