### ISSUE TITLE
Sporadic theme is incompatible with narrow navbar option

### ISSUE THREAD

**Issue by anaqreon** [DeadSuperHero/hubzilla-themes#8]
The latest Sporadic theme is incompatible with the narrow navbar option in the channel display settings. The navbar is not smaller than the full size, but the icons and nav menu items are offset.

**Comment by DeadSuperHero** [comment]
Thanks for the bug report. I've actually considered stripping out the customization settings, as a lot of the widths/heights are currently hard-coded into my themes.
